services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - PGDATA=/opt/postgres/data
    volumes:
      - ./docker-data/db:/opt/postgres/data
